-- MySQL Script generated by MySQL Workbench
-- 05/28/15 17:35:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Bestnid
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bestnid
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bestnid` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Bestnid` ;

-- -----------------------------------------------------
-- Table `Bestnid`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bestnid`.`Usuario` (
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `nro` INT NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `depto` VARCHAR(15) NULL,
  `piso` INT NULL,
  PRIMARY KEY (`nombre_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bestnid`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bestnid`.`Notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`idNotificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bestnid`.`Usuario_notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bestnid`.`Usuario_notificacion` (
  `idUsuario_notificacion` INT NOT NULL AUTO_INCREMENT,
  `Notificacion_numero_identificacion` INT NOT NULL,
  `Usuario_nombre_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario_notificacion`),
  INDEX `fk_Usuario_notificacion_Notificacion1_idx` (`Notificacion_numero_identificacion` ASC),
  INDEX `fk_Usuario_notificacion_Usuario1_idx` (`Usuario_nombre_usuario` ASC),
  CONSTRAINT `fk_Usuario_notificacion_Notificacion1`
    FOREIGN KEY (`Notificacion_numero_identificacion`)
    REFERENCES `Bestnid`.`Notificacion` (`idNotificacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Usuario_notificacion_Usuario1`
    FOREIGN KEY (`Usuario_nombre_usuario`)
    REFERENCES `Bestnid`.`Usuario` (`nombre_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bestnid`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bestnid`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bestnid`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bestnid`.`Publicacion` (
  `idPublicacion` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `finalizado` TINYINT(1) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `foto` BLOB NOT NULL,
  `Usuario_nombre_usuario` VARCHAR(45) NOT NULL,
  `Categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `fk_Publicacion_Usuario1_idx` (`Usuario_nombre_usuario` ASC),
  INDEX `fk_Publicacion_Categoria1_idx` (`Categoria_idCategoria` ASC),
  CONSTRAINT `fk_Publicacion_Usuario1`
    FOREIGN KEY (`Usuario_nombre_usuario`)
    REFERENCES `Bestnid`.`Usuario` (`nombre_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Publicacion_Categoria1`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `Bestnid`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bestnid`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bestnid`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(300) NOT NULL,
  `Usuario_nombre_usuario1` VARCHAR(45) NOT NULL,
  `Publicacion_numero_publicacion` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_Comentario_Usuario2_idx` (`Usuario_nombre_usuario1` ASC),
  INDEX `fk_Comentario_Publicacion1_idx` (`Publicacion_numero_publicacion` ASC),
  CONSTRAINT `fk_Comentario_Usuario2`
    FOREIGN KEY (`Usuario_nombre_usuario1`)
    REFERENCES `Bestnid`.`Usuario` (`nombre_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Comentario_Publicacion1`
    FOREIGN KEY (`Publicacion_numero_publicacion`)
    REFERENCES `Bestnid`.`Publicacion` (`idPublicacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bestnid`.`Oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Bestnid`.`Oferta` (
  `idOferta` INT NOT NULL,
  `motivo` VARCHAR(300) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `ganador` TINYINT(1) NULL,
  `Usuario_nombre_usuario` VARCHAR(45) NOT NULL,
  `Publicacion_idPublicacion` INT NOT NULL,
  PRIMARY KEY (`idOferta`),
  INDEX `fk_Oferta_Usuario1_idx` (`Usuario_nombre_usuario` ASC),
  INDEX `fk_Oferta_Publicacion1_idx` (`Publicacion_idPublicacion` ASC),
  CONSTRAINT `fk_Oferta_Usuario1`
    FOREIGN KEY (`Usuario_nombre_usuario`)
    REFERENCES `Bestnid`.`Usuario` (`nombre_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Oferta_Publicacion1`
    FOREIGN KEY (`Publicacion_idPublicacion`)
    REFERENCES `Bestnid`.`Publicacion` (`idPublicacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
